version: '3'

services:
  server:
    container_name: backend
    build: '.'
#    volumes:
#      - ./:/app
#      - ./node_modules:/app/node_modules
    environment:
      NODE_ENV: production
    depends_on:
      - db
    links:
      - db
    ports:
      - '3000:3000'

  db:
    image: 'mongo'
    container_name: mongo
    ports:
      - '27017:27017'